"""initial schema

Revision ID: 3ecbfcbcae2f
Revises: 
Create Date: 2026-08-13 08:12:22.425197+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '3ecbfcbcae2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('workflow_id', sa.String(length=128), nullable=True),
    sa.Column('trace_id', sa.String(length=128), nullable=True),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('next_agent_id', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('started_at_runtime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at_runtime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_request_id'), 'agent_runs', ['request_id'], unique=False)
    op.create_table('llm_call_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('workflow_id', sa.String(length=128), nullable=True),
    sa.Column('trace_id', sa.String(length=128), nullable=True),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_call_logs_request_id'), 'llm_call_logs', ['request_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('last_request_id', sa.String(length=128), nullable=True),
    sa.Column('metadata_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('task_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('workflow_id', sa.String(length=128), nullable=True),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('initial_agent_id', sa.String(length=64), nullable=False),
    sa.Column('final_agent_id', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('metadata_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_table('tool_calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('workflow_id', sa.String(length=128), nullable=True),
    sa.Column('trace_id', sa.String(length=128), nullable=True),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_calls_request_id'), 'tool_calls', ['request_id'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('workflow_id', sa.String(length=128), nullable=True),
    sa.Column('initial_agent_id', sa.String(length=64), nullable=False),
    sa.Column('current_agent_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('execution_path', sa.JSON(), nullable=False),
    sa.Column('final_agent_id', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('metadata_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_tool_calls_request_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_table('task_runs')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_llm_call_logs_request_id'), table_name='llm_call_logs')
    op.drop_table('llm_call_logs')
    op.drop_index(op.f('ix_agent_runs_request_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
