"""add llm call cost fields

Revision ID: 9b424d793e00
Revises: 3ecbfcbcae2f
Create Date: 2026-08-17 06:30:53.483681+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '9b424d793e00'
down_revision = '3ecbfcbcae2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_call_logs', sa.Column('cost_usd', sa.Float(), server_default=sa.text('0.0'), nullable=False, comment='Estimated call cost in USD from [llm].pricing.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_call_logs', 'cost_usd')
    # ### end Alembic commands ###
