"""add human review tasks

Revision ID: d821ffd3116d
Revises: e2154b5b80f5
Create Date: 2026-08-18 10:04:56.471671+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'd821ffd3116d'
down_revision = 'e2154b5b80f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_review_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('decided_by', sa.String(length=128), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index(op.f('ix_human_review_tasks_session_id'), 'human_review_tasks', ['session_id'], unique=False)
    op.create_index(op.f('ix_human_review_tasks_status'), 'human_review_tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_human_review_tasks_status'), table_name='human_review_tasks')
    op.drop_index(op.f('ix_human_review_tasks_session_id'), table_name='human_review_tasks')
    op.drop_table('human_review_tasks')
    # ### end Alembic commands ###
