"""add memory entries and session messages

Revision ID: e2154b5b80f5
Revises: 9b424d793e00
Create Date: 2026-08-18 09:18:09.343656+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'e2154b5b80f5'
down_revision = '9b424d793e00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('memory_type', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('scope_key', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('metadata_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_entries_memory_type'), 'memory_entries', ['memory_type'], unique=False)
    op.create_index(op.f('ix_memory_entries_scope'), 'memory_entries', ['scope'], unique=False)
    op.create_index(op.f('ix_memory_entries_scope_key'), 'memory_entries', ['scope_key'], unique=False)
    op.create_table('session_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('metadata_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_messages_request_id'), 'session_messages', ['request_id'], unique=False)
    op.create_index(op.f('ix_session_messages_session_id'), 'session_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_messages_session_id'), table_name='session_messages')
    op.drop_index(op.f('ix_session_messages_request_id'), table_name='session_messages')
    op.drop_table('session_messages')
    op.drop_index(op.f('ix_memory_entries_scope_key'), table_name='memory_entries')
    op.drop_index(op.f('ix_memory_entries_scope'), table_name='memory_entries')
    op.drop_index(op.f('ix_memory_entries_memory_type'), table_name='memory_entries')
    op.drop_table('memory_entries')
    # ### end Alembic commands ###
